# Generated by Django 6.0.3 on 2026-04-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inflow',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
