# Generated by Django 6.0.3 on 2026-04-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='serie_number',
            new_name='serial_number',
        ),
    ]
